---
title: "Seedling Statistics"
output: html_document
date: "2024-09-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Stats

```{r}
library(dplyr) 
library(tidyverse)
#install.packages("ggplot2")
#remove(HDR)
```

All seedling

```{r}
BRAP10_2023 <- read_csv("BRAP10-2023.csv")
BRAP06_2024 <- read_csv("BRAP06-2024.csv")
BRAP10_2024 <- read_csv("Brap10-2024.csv")

Childs10_2023 <- read_csv("Childs10-2023.csv")
Childs06_2024 <- read_csv("Childs06-2024.csv")


BRAP06_2024 <- na.omit(BRAP06_2024)
BRAP10_2023 <- na.omit(BRAP10_2023)
BRAP10_2024 <- na.omit(BRAP10_2024)

Childs10_2023 <- na.omit(Childs10_2023)
Childs06_2024 <- na.omit(Childs06_2024)

```


```{r}
#Make Values numeric
#Beasley
 BRAP06_2024 <- BRAP06_2024 %>%
  mutate(
    Height = as.numeric(Height),
    Diameter = as.numeric(Diameter),
    HDR = as.numeric(HDR)
  )

 BRAP10_2023 <- BRAP10_2023 %>%
  mutate(
    Height = as.numeric(Height),
    Diameter = as.numeric(Diameter),
    HDR = as.numeric(HDR)
  )
 
  BRAP10_2024 <- BRAP10_2024 %>%
  mutate(
    Height = as.numeric(Height),
    Diameter = as.numeric(Diameter),
    HDR = as.numeric(HDR)
  )
 
#Childs
 
Childs10_2023 <- Childs10_2023 %>%
  mutate(
    Height = as.numeric(Height),
    Diameter = as.numeric(Diameter),
    HDR = as.numeric(HDR)
  )

Childs06_2024 <- Childs06_2024 %>%
  mutate(
    Height = as.numeric(`Height`),
    Diameter = as.numeric(`Diameter`),
    HDR = as.numeric(`HDR`)
  )
 
```

Stats

```{r}


cor(BRAPHDR2023, BRAPHDR2024)

```

# Plots

Clean data

```{r}
# Extract the columns you need
ChildsHDR2023 <- Childs10_2023[, 6]
ChildsHDR2024 <- Childs06_2024[, 6]

BRAPHDR2023 <- BRAP10_2023[,6]
BRAPHDR06_2024 <- BRAP06_2024[,6]
BRAPHDR10_2024 <- BRAP10_2024[,3]


#Clean Data Childs

ChildsHDR2024 <- unlist(ChildsHDR2024)
ChildsHDR2024 <- na.omit(ChildsHDR2024)
ChildsHDR2023 <- unlist(ChildsHDR2023)
ChildsHDR2023<- na.omit(ChildsHDR2023)

BRAPHDR2023 <- na.omit(BRAPHDR2023)
BRAPHDR2023 <- unlist(BRAPHDR2023)
BRAPHDR06_2024 <- na.omit(BRAPHDR2024)
BRAPHDR06_2024 <- unlist(BRAPHDR2024)
BRAPHDR10_2024 <- unlist(BRAPHDR10_2024)
BRAPHDR10_2024 <- na.omit(BRAPHDR10_2024)


```


Hist Childs

```{r}
# Set up the plotting area to have 1 row and 2 columns
par(mfrow = c(2, 2))

# Create the first histogram
hist(ChildsHDR2023, 
     main = "Histogram of Childs HDR 2023", 
     xlab = "Height to Diameter Ratio", 
     col = "grey", 
     breaks = "Sturges")

# Create the second histogram
hist(ChildsHDR2024, 
     main = "Histogram of Childs HDR 2024",
     xlab = "Height to Diameter Ratio", 
     col = "grey", 
     breaks = "Sturges")


# Create the first histogram
hist(BRAPHDR2023, 
     main = "Histogram of BRAPHDR2023", 
     xlab = "Height to Diameter Ratio", 
     col = "grey22", 
     breaks = "Sturges")

# Create the second histogram
hist(BRAPHDR06_2024, 
     main = "Histogram of BRAPHDR2024", 
     xlab = "Height to Diameter Ratio", 
     col = "grey22", 
     breaks = "Sturges")

hist(BRAPHDR06_2024, 
     main = "Histogram of BRAPHDR2024", 
     xlab = "Height to Diameter Ratio", 
     col = "grey22", 
     breaks = "Sturges")


# Reset plotting area to default
par(mfrow = c(2, 3))




```


Summary Stats

Tables
```{r}
#Beasley Table

# Summarize and calculate means for specific columns
BRAP06_2024_table <- BRAP06_2024 %>%
  summarise(
    Height = mean(Height, na.rm = TRUE),
    Diameter = mean(Diameter, na.rm = TRUE),
    HDR = mean(HDR, na.rm = TRUE)
  )
BRAP2023_table <- BRAP10_2023 %>%
  summarise(
    Height = mean(Height, na.rm = TRUE),
    Diameter = mean(Diameter, na.rm = TRUE),
    HDR = mean(HDR, na.rm = TRUE)
  )

BRAP10_2024_table <- BRAP10_2024 %>%
  summarise(
    Height = mean(Height, na.rm = TRUE),
    Diameter = mean(Diameter, na.rm = TRUE),
    HDR = mean(HDR, na.rm = TRUE)
  )

BRAP_TABLE <- rbind(BRAP2023_table,BRAP06_2024_table,BRAP10_2024_table)



print(BRAP_TABLE)
```

Childs tables
```{r}
# Summarize and calculate means for specific columns
CHILDS06_2024_table <- Childs06_2024 %>%
  summarise(
    Height = mean(Height, na.rm = TRUE),
    Diameter = mean(Diameter, na.rm = TRUE),
    HDR = mean(HDR, na.rm = TRUE)
  )
CHILDS2023_table <- Childs10_2023 %>%
  summarise(
    Height = mean(Height, na.rm = TRUE),
    Diameter = mean(Diameter, na.rm = TRUE),
    HDR = mean(HDR, na.rm = TRUE)
  )



Childs_TABLE <- rbind(CHILDS2023_table,CHILDS06_2024_table)



print(Childs_TABLE)



```







