---
title: "USGS Flow stats"
output: html_document
date: "2024-09-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("dataRetrieval")
library(dataRetrieval)
library(ggplot2)
library(dplyr)
library(lubridate)
```


Download USGS
```{r}
CampVerdeGuage <- readNWISdv(    #Daily
  "09506000",                  #Below camp verde guage
  "00060",                      #Discharge
  startDate = "1991-01-01",      #From first complete year
  endDate = "2006-01-01",                 #Till now
  statCd = "00003"
)
CampVerdeGuage <- CampVerdeGuage %>%     #Rename column to discharge
  rename(Discharge = X_00060_00003)
```



```{r}
# Get the top 5 highest flows
top_flows <- CampVerdeGuage %>%
  arrange(desc(Discharge)) %>%  # Sort by flow (descending)
  slice(1:10)  # Select top 5 rows

# Print results
print(top_flows)

```


AEP
```{r fig.height=8, fig.width=20}

ggplot(data = CampVerdeGuage, mapping = aes(x = Date, y = Discharge)) + 
    scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
  geom_line()+
geom_hline(yintercept = 24800, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" , x = as.Date("1990-04-01"), y = 24800, label ="20% AEP"
             , color ="black", vjust =-1, size = 5)+
   annotate("text" , x = as.Date("2006-01-01"), y = 24800, label ="5 year flood"
             , color ="black", vjust =-1, size = 5)+
geom_hline(yintercept  = 42500, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("1990-04-01"), y = 42500, label ="10% AEP"
             , color ="black", vjust =-1, size = 5)+
  annotate("text" , x = as.Date("2006-01-01"), y = 42500, label ="10 year flood"
             , color ="black", vjust =-1, size = 5)+
  geom_hline(yintercept = 75100, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("1990-04-01"), y = 75100, label ="4% AEP"
             , color ="black", vjust =-1, size = 5)+
  annotate("text" , x = as.Date("2006-01-01"), y = 75100, label ="25 year flood"
             , color ="black", vjust =-1, size = 5)+
  geom_hline(yintercept = 108000, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("1990-04-01"), y = 108000, label ="2% AEP"
             , color ="black", vjust =-1, size = 5)+
    annotate("text" , x = as.Date("2006-01-01"), y = 108000, label ="50 year flood"
             , color ="black", vjust =-1, size = 5)+
  annotate("text" , x = as.Date("2006-01-01"), y = 75100, label ="50 year flood"
             , color ="black", vjust =-1, size = 5)+
  geom_point(aes(x=as.Date("1993-02-20") , y= 101000 ),shape= 18, size= 5, color = "black")+
    geom_point(aes(x=as.Date("1995-03-6") , y= 75500 ),shape= 18, size= 5, color = "black")+
    geom_point(aes(x=as.Date("2005-02-12") , y= 62000 ),shape= 18, size= 5, color = "black")+
  theme_minimal() +
  theme(text = element_text(size = 20))  # Increase all text size




```



Water rights filing
```{r fig.height=5, fig.width=9}
ggplot(data = CampVerdeGuage, mapping = aes(x = Date, y = Discharge)) + 
  geom_line()+
geom_hline(yintercept = 26200, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" , x = as.Date("1991-07-01"), y = 26200, label ="Late Winter/Spring flood"
             , color ="black", vjust =-1, size = 3)+
geom_hline(yintercept  = 10500, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("1991-04-01"), y = 10500, label ="Rejuvenating FLood"
             , color ="black", vjust =-1, size = 3)+
geom_hline(yintercept = 52700, color = "blue", linetype = "dashed", size = 1)+
  annotate("text" , x = as.Date("1991-04-01"), y = 52700, label ="Restructuring flood"
             , color ="black", vjust =-1, size = 3)+
  geom_point(aes(x=as.Date("1993-02-20") , y= 101000 ),shape= 18, size= 5, color = "black")+
    geom_point(aes(x=as.Date("1995-03-6") , y= 75500 ),shape= 18, size= 5, color = "black")+
    geom_point(aes(x=as.Date("2005-02-12") , y= 62000 ),shape= 18, size= 5, color = "black")+
  theme_minimal()



```

both
```{r fig.height=5, fig.width=9}
ggplot(data = CampVerdeGuage, mapping = aes(x = Date, y = Discharge)) + 
  geom_line()+
geom_hline(yintercept = 26200, color = "red", linetype = "dashed", size = 1)+
    annotate("text" , x = as.Date("2006-04-01"), y = 24800, label ="Late Spring flood"
             , color ="black", vjust =-1, size = 3)+
  geom_hline(yintercept = 1240, color = "red", linetype = "dashed", size = 1)+
   annotate("text" , x = as.Date("2006-01-01"), y = 1240, label ="Spring and Fall flood pulse"
             , color ="black", vjust =-1, size = 3)+
geom_hline(yintercept  = 42500, color = "red", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("2006-04-01"), y = 42500, label ="Rejuvenating FLood"
             , color ="black", vjust =-1, size = 3)+
  geom_hline(yintercept  = 52700, color = "red", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("2006-04-01"), y = 52700, label ="Restructuring"
             , color ="black", vjust =-1, size = 3)+
  #AEP
geom_hline(yintercept = 24800, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" , x = as.Date("1990-04-01"), y = 24800, label ="20% AEP"
             , color ="black", vjust =-1, size = 3)+
geom_hline(yintercept  = 42500, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("1990-04-01"), y = 42500, label ="10% AEP"
             , color ="black", vjust =-1, size = 3)+
  geom_hline(yintercept = 75100, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("1990-04-01"), y = 75100, label ="4% AEP"
             , color ="black", vjust =-1, size = 3)+
  geom_hline(yintercept = 108000, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("1990-04-01"), y = 108000, label ="2% AEP"
             , color ="black", vjust =-1, size = 3)+
  geom_point(aes(x=as.Date("1993-02-20") , y= 101000 ),shape= 18, size= 5, color = "black")+
    geom_point(aes(x=as.Date("1995-03-6") , y= 75500 ),shape= 18, size= 5, color = "black")+
    geom_point(aes(x=as.Date("2005-02-12") , y= 62000 ),shape= 18, size= 5, color = "black")+
  theme_minimal()



```



Water rights filing
```{r}
ggplot(data = CampVerdeGuage, mapping = aes(x = Date, y = Discharge)) + 
  geom_line()+
geom_hline(yintercept = 26200, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" , x = as.Date("1990-04-01"), y = 24800, label ="Late Spring flood"
             , color ="black", vjust =-1, size = 3)+
   annotate("text" , x = as.Date("2006-01-01"), y = 1240, label ="Spring and Fall flood pulse"
             , color ="black", vjust =-1, size = 3)+
geom_hline(yintercept  = 10500, color = "blue", linetype = "dashed", size = 1)+
    annotate("text" ,x = as.Date("1990-04-01"), y = 42500, label ="Rejuvenating FLood"
             , color ="black", vjust =-1, size = 3)+
  annotate("text" , x = as.Date("2006-01-01"), y = 52700, label ="Restructuring flood"
             , color ="black", vjust =-1, size = 3)+
  geom_hline(yintercept = 108000, color = "blue", linetype = "dashed", size = 1)+
  geom_point(aes(x=as.Date("1993-02-20") , y= 101000 ),shape= 18, size= 5, color = "black")+
    geom_point(aes(x=as.Date("1995-03-6") , y= 75500 ),shape= 18, size= 5, color = "black")+
    geom_point(aes(x=as.Date("2005-02-12") , y= 62000 ),shape= 18, size= 5, color = "black")+
  
  theme_minimal()



```


Mean annual values
```{r}
# Calculate mean annual values
annual_means <- CampVerdeGuage %>%
  group_by(year = year(Date)) %>%  # Corrected here
  summarise(mean_value = mean(Discharge, na.rm = TRUE))  # Replace 'Discharge' with your parameter name

annual_means <- setNames(annual_means, c("Year", "Mean"))
```



Mean Winter flows November-march
```{r}
# Extract year and month
CampVerdeGuage$Year <- format(CampVerdeGuage$Date, "%Y")
CampVerdeGuage$Month <- format(CampVerdeGuage$Date, "%m")

# Filter for months between November and March
winter_data <- CampVerdeGuage %>%
  filter(Month %in% c("11", "12", "01", "02", "03"))
mean_winter_flow <- winter_data %>%
  group_by(Year) %>%
  summarise(mean_winter_flow = mean(Discharge, na.rm = TRUE)) 

```

Summer flows
```{r}
SummerFlows<- CampVerdeGuage %>%
  filter(Month %in% c("06", "07", "08", "09"))
SummerFlows <- SummerFlows %>%
  group_by(Year) %>%
  summarise(SummerFlows = mean(Discharge, na.rm = TRUE)) 
```


min flow
```{r}
meanmin <- CampVerdeGuage %>%
  group_by(year = year(Date)) %>%  # Corrected here
  summarise(min = min(Discharge, na.rm = TRUE))  # Replace 'Discharge' with your parameter name
```

Max flow
```{r}
maxflow <- CampVerdeGuage %>%
  group_by(year = year(Date)) %>%  # Corrected here
  summarise(max = max(Discharge, na.rm = TRUE))
```


Monthly means
```{r}

monthly_means <- CampVerdeGuage %>%
  mutate(Year = year(Date), Month = month(Date)) %>%
  group_by(Year, Month) %>%
  summarise(Monthly_Mean = mean(Discharge, na.rm = TRUE), .groups = "drop")

monthly_means <- monthly_means %>%
  pivot_wider(names_from = Month, values_from = Monthly_Mean, names_prefix = "Month_") %>%
  arrange(Year)

# Rename the columns to use month names
month_names <- c("January", "February", "March", "April", "May", "June", 
                 "July", "August", "September", "October", "November", "December")

# Assign the month names to the columns (excluding "Year" column)
colnames(monthly_means)[2:13] <- month_names




```






Mean PDSI Yavapai County Yearly

```{r}
PDSI <- read_csv("PDSI-AZ-1994to2023.csv")

PDSImean <- PDSI %>%
  group_by(Year, Month) %>%
  summarise(mean_value = mean(`Value`, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(names_from = Month, values_from = mean_value, names_prefix = "Month_") %>%
  arrange(Year)

# Rename columns to month names
month_names <- c("January", "February", "March", "April", "May", "June", 
                 "July", "August", "September", "October", "November", "December")

# Assign the month names to the columns (excluding the "Year" column)
colnames(PDSImean)[2:13] <- month_names

remove(PDSI)

```


Mean Yearly Temp Yavapai county


```{r}

YearlyTemp <- read.csv("AverageMonthlyTemp-YavapaiCounty_1993-2024.csv")

MeanTemp <- YearlyTemp %>%
  group_by(Year, Month) %>%
  summarise(mean_value = mean(`Value`, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(names_from = Month, values_from = mean_value, names_prefix = "Month_") %>%
  arrange(Year)

# Rename columns to month names
month_names <- c("January", "February", "March", "April", "May", "June", 
                 "July", "August", "September", "October", "November", "December")

# Assign the month names to the columns (excluding the "Year" column)
colnames(MeanTemp)[2:13] <- month_names

# View the resulting data
print(MeanTemp)

remove(YearlyTemp)
```


```{r}
Precip <- read.csv("YavapaiPrecip.csv")


Precip <- Precip %>%
  group_by(Year, Month) %>%
  summarise(mean_value = mean(`Value`, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(names_from = Month, values_from = mean_value, names_prefix = "Month_") %>%
  arrange(Year)

# Rename columns to month names
month_names <- c("January", "February", "March", "April", "May", "June", 
                 "July", "August", "September", "October", "November", "December")

# Assign the month names to the columns (excluding the "Year" column)
colnames(Precip)[2:13] <- month_names

# View the resulting data
print(Precip)


```

Min temp









